/*
 * SeminarCatalog API
 * Rest API for SeminarCatalog Administration
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@databay.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.12
 *
 * Do not edit the class manually.
 */

import {ApiClient} from '../ApiClient';

/**
 * The ProviderInfo model module.
 * @module model/ProviderInfo
 * @version 1.0.0
 */
export class ProviderInfo {
  /**
   * Constructs a new <code>ProviderInfo</code>.
   * @alias module:model/ProviderInfo
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ProviderInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ProviderInfo} obj Optional instance to populate.
   * @return {module:model/ProviderInfo} The populated <code>ProviderInfo</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ProviderInfo();
      if (data.hasOwnProperty('_syncFields'))
        obj.syncFields = ApiClient.convertToType(data['_syncFields'], ['String']);
      if (data.hasOwnProperty('label'))
        obj.label = ApiClient.convertToType(data['label'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('value'))
        obj.value = ApiClient.convertToType(data['value'], 'String');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('foreignId'))
        obj.foreignId = ApiClient.convertToType(data['foreignId'], 'String');
      if (data.hasOwnProperty('language'))
        obj.language = ApiClient.convertToType(data['language'], 'Number');
      if (data.hasOwnProperty('createDate'))
        obj.createDate = ApiClient.convertToType(data['createDate'], 'Number');
      if (data.hasOwnProperty('changeDate'))
        obj.changeDate = ApiClient.convertToType(data['changeDate'], 'Number');
      if (data.hasOwnProperty('deleted'))
        obj.deleted = ApiClient.convertToType(data['deleted'], 'Number');
      if (data.hasOwnProperty('hidden'))
        obj.hidden = ApiClient.convertToType(data['hidden'], 'Number');
      if (data.hasOwnProperty('sorting'))
        obj.sorting = ApiClient.convertToType(data['sorting'], 'Number');
      if (data.hasOwnProperty('tags'))
        obj.tags = ApiClient.convertToType(data['tags'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Array.<String>} syncFields
 */
ProviderInfo.prototype.syncFields = undefined;

/**
 * @member {String} label
 */
ProviderInfo.prototype.label = undefined;

/**
 * @member {String} name
 */
ProviderInfo.prototype.name = undefined;

/**
 * @member {String} value
 */
ProviderInfo.prototype.value = undefined;

/**
 * @member {Number} id
 */
ProviderInfo.prototype.id = undefined;

/**
 * @member {String} foreignId
 */
ProviderInfo.prototype.foreignId = undefined;

/**
 * @member {Number} language
 */
ProviderInfo.prototype.language = undefined;

/**
 * @member {Number} createDate
 */
ProviderInfo.prototype.createDate = undefined;

/**
 * @member {Number} changeDate
 */
ProviderInfo.prototype.changeDate = undefined;

/**
 * @member {Number} deleted
 */
ProviderInfo.prototype.deleted = undefined;

/**
 * @member {Number} hidden
 */
ProviderInfo.prototype.hidden = undefined;

/**
 * @member {Number} sorting
 */
ProviderInfo.prototype.sorting = undefined;

/**
 * @member {String} tags
 */
ProviderInfo.prototype.tags = undefined;


