/*
 * SeminarCatalog API
 * Rest API for SeminarCatalog Administration
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@databay.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.12
 *
 * Do not edit the class manually.
 */

import {ApiClient} from '../ApiClient';

/**
 * The Topic model module.
 * @module model/Topic
 * @version 1.0.0
 */
export class Topic {
  /**
   * Constructs a new <code>Topic</code>.
   * @alias module:model/Topic
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Topic</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Topic} obj Optional instance to populate.
   * @return {module:model/Topic} The populated <code>Topic</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Topic();
      if (data.hasOwnProperty('_syncFields'))
        obj.syncFields = ApiClient.convertToType(data['_syncFields'], ['String']);
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('code'))
        obj.code = ApiClient.convertToType(data['code'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('intro'))
        obj.intro = ApiClient.convertToType(data['intro'], 'String');
      if (data.hasOwnProperty('content'))
        obj.content = ApiClient.convertToType(data['content'], 'String');
      if (data.hasOwnProperty('hideInCatalog'))
        obj.hideInCatalog = ApiClient.convertToType(data['hideInCatalog'], 'Number');
      if (data.hasOwnProperty('hideInFilter'))
        obj.hideInFilter = ApiClient.convertToType(data['hideInFilter'], 'Number');
      if (data.hasOwnProperty('numberRangeCurrent'))
        obj.numberRangeCurrent = ApiClient.convertToType(data['numberRangeCurrent'], 'Number');
      if (data.hasOwnProperty('numberRangeMax'))
        obj.numberRangeMax = ApiClient.convertToType(data['numberRangeMax'], 'Number');
      if (data.hasOwnProperty('numberRangeMin'))
        obj.numberRangeMin = ApiClient.convertToType(data['numberRangeMin'], 'Number');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('foreignId'))
        obj.foreignId = ApiClient.convertToType(data['foreignId'], 'String');
      if (data.hasOwnProperty('language'))
        obj.language = ApiClient.convertToType(data['language'], 'Number');
      if (data.hasOwnProperty('createDate'))
        obj.createDate = ApiClient.convertToType(data['createDate'], 'Number');
      if (data.hasOwnProperty('changeDate'))
        obj.changeDate = ApiClient.convertToType(data['changeDate'], 'Number');
      if (data.hasOwnProperty('deleted'))
        obj.deleted = ApiClient.convertToType(data['deleted'], 'Number');
      if (data.hasOwnProperty('hidden'))
        obj.hidden = ApiClient.convertToType(data['hidden'], 'Number');
      if (data.hasOwnProperty('sorting'))
        obj.sorting = ApiClient.convertToType(data['sorting'], 'Number');
      if (data.hasOwnProperty('tags'))
        obj.tags = ApiClient.convertToType(data['tags'], 'String');
      if (data.hasOwnProperty('glyphicon'))
        obj.glyphicon = ApiClient.convertToType(data['glyphicon'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Array.<String>} syncFields
 */
Topic.prototype.syncFields = undefined;

/**
 * @member {String} name
 */
Topic.prototype.name = undefined;

/**
 * @member {String} code
 */
Topic.prototype.code = undefined;

/**
 * @member {String} description
 */
Topic.prototype.description = undefined;

/**
 * @member {String} intro
 */
Topic.prototype.intro = undefined;

/**
 * @member {String} content
 */
Topic.prototype.content = undefined;

/**
 * @member {Number} hideInCatalog
 */
Topic.prototype.hideInCatalog = undefined;

/**
 * @member {Number} hideInFilter
 */
Topic.prototype.hideInFilter = undefined;

/**
 * @member {Number} numberRangeCurrent
 */
Topic.prototype.numberRangeCurrent = undefined;

/**
 * @member {Number} numberRangeMax
 */
Topic.prototype.numberRangeMax = undefined;

/**
 * @member {Number} numberRangeMin
 */
Topic.prototype.numberRangeMin = undefined;

/**
 * @member {Number} id
 */
Topic.prototype.id = undefined;

/**
 * @member {String} foreignId
 */
Topic.prototype.foreignId = undefined;

/**
 * @member {Number} language
 */
Topic.prototype.language = undefined;

/**
 * @member {Number} createDate
 */
Topic.prototype.createDate = undefined;

/**
 * @member {Number} changeDate
 */
Topic.prototype.changeDate = undefined;

/**
 * @member {Number} deleted
 */
Topic.prototype.deleted = undefined;

/**
 * @member {Number} hidden
 */
Topic.prototype.hidden = undefined;

/**
 * @member {Number} sorting
 */
Topic.prototype.sorting = undefined;

/**
 * @member {String} tags
 */
Topic.prototype.tags = undefined;

/**
 * @member {String} glyphicon
 */
Topic.prototype.glyphicon = undefined;


