/*
 * SeminarCatalog API
 * Rest API for SeminarCatalog Administration
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@databay.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.12
 *
 * Do not edit the class manually.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SeminarCatalogApi);
  }
}(this, function(expect, SeminarCatalogApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SeminarCatalogApi.CountryInternalApi();
  });

  describe('(package)', function() {
    describe('CountryInternalApi', function() {
      describe('countryCreate', function() {
        it('should call countryCreate successfully', function(done) {
          // TODO: uncomment countryCreate call and complete the assertions
          /*

          instance.countryCreate().then(function(data) {
            // TODO: update response assertions
            expect(data).to.be.a(SeminarCatalogApi.Country);
            {
              let dataCtr = data.syncFields;
              expect(dataCtr).to.be.an(Array);
              expect(dataCtr).to.not.be.empty();
              for (let p in dataCtr) {
                let data = dataCtr[p];
                expect(data).to.be.a('string');
                // expect(data).to.be("");
              }
            }
            expect(data.code).to.be.a('string');
            // expect(data.code).to.be("");
            expect(data.name).to.be.a('string');
            // expect(data.name).to.be("");
            expect(data.localName).to.be.a('string');
            // expect(data.localName).to.be("");
            expect(data.englishName).to.be.a('number');
            // expect(data.englishName).to.be(0);
            expect(data.isEuMember).to.be.a('string');
            // expect(data.isEuMember).to.be("");
            expect(data.termsAndConditions).to.be.a('string');
            // expect(data.termsAndConditions).to.be("");
            expect(data.privacyPolicy).to.be.a('string');
            // expect(data.privacyPolicy).to.be("");
            expect(data.cancellationInfo).to.be.a('string');
            // expect(data.cancellationInfo).to.be("");
            expect(data.defaultCountry).to.be.a('number');
            // expect(data.defaultCountry).to.be(0);
            expect(data.isFavorite).to.be.a('number');
            // expect(data.isFavorite).to.be(0);
            expect(data.id).to.be.a('number');
            // expect(data.id).to.be(0);
            expect(data.foreignId).to.be.a('string');
            // expect(data.foreignId).to.be("");
            expect(data.language).to.be.a('number');
            // expect(data.language).to.be(0);
            expect(data.createDate).to.be.a('number');
            // expect(data.createDate).to.be(0);
            expect(data.changeDate).to.be.a('number');
            // expect(data.changeDate).to.be(0);
            expect(data.deleted).to.be.a('number');
            // expect(data.deleted).to.be(0);
            expect(data.hidden).to.be.a('number');
            // expect(data.hidden).to.be(0);
            expect(data.sorting).to.be.a('number');
            // expect(data.sorting).to.be(0);
            expect(data.tags).to.be.a('string');
            // expect(data.tags).to.be("");

            done();
          }, function(error) {
            done(error);
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('countryDelete', function() {
        it('should call countryDelete successfully', function(done) {
          // TODO: uncomment, update parameter values for countryDelete call and complete the assertions
          /*
          var id = 56;

          instance.countryDelete(id).then(function(data) {
            // TODO: update response assertions
            expect(data).to.be.a(SeminarCatalogApi.Country);
            {
              let dataCtr = data.syncFields;
              expect(dataCtr).to.be.an(Array);
              expect(dataCtr).to.not.be.empty();
              for (let p in dataCtr) {
                let data = dataCtr[p];
                expect(data).to.be.a('string');
                // expect(data).to.be("");
              }
            }
            expect(data.code).to.be.a('string');
            // expect(data.code).to.be("");
            expect(data.name).to.be.a('string');
            // expect(data.name).to.be("");
            expect(data.localName).to.be.a('string');
            // expect(data.localName).to.be("");
            expect(data.englishName).to.be.a('number');
            // expect(data.englishName).to.be(0);
            expect(data.isEuMember).to.be.a('string');
            // expect(data.isEuMember).to.be("");
            expect(data.termsAndConditions).to.be.a('string');
            // expect(data.termsAndConditions).to.be("");
            expect(data.privacyPolicy).to.be.a('string');
            // expect(data.privacyPolicy).to.be("");
            expect(data.cancellationInfo).to.be.a('string');
            // expect(data.cancellationInfo).to.be("");
            expect(data.defaultCountry).to.be.a('number');
            // expect(data.defaultCountry).to.be(0);
            expect(data.isFavorite).to.be.a('number');
            // expect(data.isFavorite).to.be(0);
            expect(data.id).to.be.a('number');
            // expect(data.id).to.be(0);
            expect(data.foreignId).to.be.a('string');
            // expect(data.foreignId).to.be("");
            expect(data.language).to.be.a('number');
            // expect(data.language).to.be(0);
            expect(data.createDate).to.be.a('number');
            // expect(data.createDate).to.be(0);
            expect(data.changeDate).to.be.a('number');
            // expect(data.changeDate).to.be(0);
            expect(data.deleted).to.be.a('number');
            // expect(data.deleted).to.be(0);
            expect(data.hidden).to.be.a('number');
            // expect(data.hidden).to.be(0);
            expect(data.sorting).to.be.a('number');
            // expect(data.sorting).to.be(0);
            expect(data.tags).to.be.a('string');
            // expect(data.tags).to.be("");

            done();
          }, function(error) {
            done(error);
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('countryGet', function() {
        it('should call countryGet successfully', function(done) {
          // TODO: uncomment, update parameter values for countryGet call and complete the assertions
          /*
          var id = 56;

          instance.countryGet(id).then(function(data) {
            // TODO: update response assertions
            expect(data).to.be.a(SeminarCatalogApi.Country);
            {
              let dataCtr = data.syncFields;
              expect(dataCtr).to.be.an(Array);
              expect(dataCtr).to.not.be.empty();
              for (let p in dataCtr) {
                let data = dataCtr[p];
                expect(data).to.be.a('string');
                // expect(data).to.be("");
              }
            }
            expect(data.code).to.be.a('string');
            // expect(data.code).to.be("");
            expect(data.name).to.be.a('string');
            // expect(data.name).to.be("");
            expect(data.localName).to.be.a('string');
            // expect(data.localName).to.be("");
            expect(data.englishName).to.be.a('number');
            // expect(data.englishName).to.be(0);
            expect(data.isEuMember).to.be.a('string');
            // expect(data.isEuMember).to.be("");
            expect(data.termsAndConditions).to.be.a('string');
            // expect(data.termsAndConditions).to.be("");
            expect(data.privacyPolicy).to.be.a('string');
            // expect(data.privacyPolicy).to.be("");
            expect(data.cancellationInfo).to.be.a('string');
            // expect(data.cancellationInfo).to.be("");
            expect(data.defaultCountry).to.be.a('number');
            // expect(data.defaultCountry).to.be(0);
            expect(data.isFavorite).to.be.a('number');
            // expect(data.isFavorite).to.be(0);
            expect(data.id).to.be.a('number');
            // expect(data.id).to.be(0);
            expect(data.foreignId).to.be.a('string');
            // expect(data.foreignId).to.be("");
            expect(data.language).to.be.a('number');
            // expect(data.language).to.be(0);
            expect(data.createDate).to.be.a('number');
            // expect(data.createDate).to.be(0);
            expect(data.changeDate).to.be.a('number');
            // expect(data.changeDate).to.be(0);
            expect(data.deleted).to.be.a('number');
            // expect(data.deleted).to.be(0);
            expect(data.hidden).to.be.a('number');
            // expect(data.hidden).to.be(0);
            expect(data.sorting).to.be.a('number');
            // expect(data.sorting).to.be(0);
            expect(data.tags).to.be.a('string');
            // expect(data.tags).to.be("");

            done();
          }, function(error) {
            done(error);
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('countryList', function() {
        it('should call countryList successfully', function(done) {
          // TODO: uncomment countryList call and complete the assertions
          /*

          instance.countryList().then(function(data) {
            // TODO: update response assertions
            expect(data).to.be.a(SeminarCatalogApi.CountryPaginationResult);
            expect(data.limit).to.be.a('number');
            // expect(data.limit).to.be(0);
            expect(data.offset).to.be.a('number');
            // expect(data.offset).to.be(0);
            expect(data.entryCount).to.be.a('number');
            // expect(data.entryCount).to.be(0);
            expect(data.maxEntryCount).to.be.a('number');
            // expect(data.maxEntryCount).to.be(0);
            {
              let dataCtr = data.entries;
              expect(dataCtr).to.be.an(Array);
              expect(dataCtr).to.not.be.empty();
              for (let p in dataCtr) {
                let data = dataCtr[p];
                expect(data).to.be.a(SeminarCatalogApi.Country);
                {
                  let dataCtr = data.syncFields;
                  expect(dataCtr).to.be.an(Array);
                  expect(dataCtr).to.not.be.empty();
                  for (let p in dataCtr) {
                    let data = dataCtr[p];
                    expect(data).to.be.a('string');
                    // expect(data).to.be("");
                  }
                }
                expect(data.code).to.be.a('string');
                // expect(data.code).to.be("");
                expect(data.name).to.be.a('string');
                // expect(data.name).to.be("");
                expect(data.localName).to.be.a('string');
                // expect(data.localName).to.be("");
                expect(data.englishName).to.be.a('number');
                // expect(data.englishName).to.be(0);
                expect(data.isEuMember).to.be.a('string');
                // expect(data.isEuMember).to.be("");
                expect(data.termsAndConditions).to.be.a('string');
                // expect(data.termsAndConditions).to.be("");
                expect(data.privacyPolicy).to.be.a('string');
                // expect(data.privacyPolicy).to.be("");
                expect(data.cancellationInfo).to.be.a('string');
                // expect(data.cancellationInfo).to.be("");
                expect(data.defaultCountry).to.be.a('number');
                // expect(data.defaultCountry).to.be(0);
                expect(data.isFavorite).to.be.a('number');
                // expect(data.isFavorite).to.be(0);
                expect(data.id).to.be.a('number');
                // expect(data.id).to.be(0);
                expect(data.foreignId).to.be.a('string');
                // expect(data.foreignId).to.be("");
                expect(data.language).to.be.a('number');
                // expect(data.language).to.be(0);
                expect(data.createDate).to.be.a('number');
                // expect(data.createDate).to.be(0);
                expect(data.changeDate).to.be.a('number');
                // expect(data.changeDate).to.be(0);
                expect(data.deleted).to.be.a('number');
                // expect(data.deleted).to.be(0);
                expect(data.hidden).to.be.a('number');
                // expect(data.hidden).to.be(0);
                expect(data.sorting).to.be.a('number');
                // expect(data.sorting).to.be(0);
                expect(data.tags).to.be.a('string');
                // expect(data.tags).to.be("");
              }
            }

            done();
          }, function(error) {
            done(error);
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('countryUpdate', function() {
        it('should call countryUpdate successfully', function(done) {
          // TODO: uncomment, update parameter values for countryUpdate call and complete the assertions
          /*
          var id = 56;

          instance.countryUpdate(id).then(function(data) {
            // TODO: update response assertions
            expect(data).to.be.a(SeminarCatalogApi.Country);
            {
              let dataCtr = data.syncFields;
              expect(dataCtr).to.be.an(Array);
              expect(dataCtr).to.not.be.empty();
              for (let p in dataCtr) {
                let data = dataCtr[p];
                expect(data).to.be.a('string');
                // expect(data).to.be("");
              }
            }
            expect(data.code).to.be.a('string');
            // expect(data.code).to.be("");
            expect(data.name).to.be.a('string');
            // expect(data.name).to.be("");
            expect(data.localName).to.be.a('string');
            // expect(data.localName).to.be("");
            expect(data.englishName).to.be.a('number');
            // expect(data.englishName).to.be(0);
            expect(data.isEuMember).to.be.a('string');
            // expect(data.isEuMember).to.be("");
            expect(data.termsAndConditions).to.be.a('string');
            // expect(data.termsAndConditions).to.be("");
            expect(data.privacyPolicy).to.be.a('string');
            // expect(data.privacyPolicy).to.be("");
            expect(data.cancellationInfo).to.be.a('string');
            // expect(data.cancellationInfo).to.be("");
            expect(data.defaultCountry).to.be.a('number');
            // expect(data.defaultCountry).to.be(0);
            expect(data.isFavorite).to.be.a('number');
            // expect(data.isFavorite).to.be(0);
            expect(data.id).to.be.a('number');
            // expect(data.id).to.be(0);
            expect(data.foreignId).to.be.a('string');
            // expect(data.foreignId).to.be("");
            expect(data.language).to.be.a('number');
            // expect(data.language).to.be(0);
            expect(data.createDate).to.be.a('number');
            // expect(data.createDate).to.be(0);
            expect(data.changeDate).to.be.a('number');
            // expect(data.changeDate).to.be(0);
            expect(data.deleted).to.be.a('number');
            // expect(data.deleted).to.be(0);
            expect(data.hidden).to.be.a('number');
            // expect(data.hidden).to.be(0);
            expect(data.sorting).to.be.a('number');
            // expect(data.sorting).to.be(0);
            expect(data.tags).to.be.a('string');
            // expect(data.tags).to.be("");

            done();
          }, function(error) {
            done(error);
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
