/*
 * SeminarCatalog API
 * Rest API for SeminarCatalog Administration
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@databay.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.12
 *
 * Do not edit the class manually.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SeminarCatalogApi);
  }
}(this, function(expect, SeminarCatalogApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SeminarCatalogApi.TestInternalApi();
  });

  describe('(package)', function() {
    describe('TestInternalApi', function() {
      describe('testCreate', function() {
        it('should call testCreate successfully', function(done) {
          // TODO: uncomment testCreate call and complete the assertions
          /*

          instance.testCreate().then(function(data) {
            // TODO: update response assertions
            expect(data).to.be.a(SeminarCatalogApi.Test);
            expect(data.syncFields).to.be.a('string');
            // expect(data.syncFields).to.be("");
            expect(data.title).to.be.a('string');
            // expect(data.title).to.be("");
            expect(data.description).to.be.a('string');
            // expect(data.description).to.be("");
            expect(data.type).to.be.a('number');
            // expect(data.type).to.be(0);
            expect(data.mandatory).to.be.a('number');
            // expect(data.mandatory).to.be(0);
            expect(data.maxPoints).to.be.a('number');
            // expect(data.maxPoints).to.be(0);
            expect(data.passmarkPercentage).to.be.a('number');
            // expect(data.passmarkPercentage).to.be(0);
            expect(data.specificTestId).to.be.a('string');
            // expect(data.specificTestId).to.be("");
            expect(data.id).to.be.a('number');
            // expect(data.id).to.be(0);
            expect(data.foreignId).to.be.a('string');
            // expect(data.foreignId).to.be("");
            expect(data.language).to.be.a('number');
            // expect(data.language).to.be(0);
            expect(data.createDate).to.be.a('number');
            // expect(data.createDate).to.be(0);
            expect(data.changeDate).to.be.a('number');
            // expect(data.changeDate).to.be(0);
            expect(data.deleted).to.be.a('number');
            // expect(data.deleted).to.be(0);
            expect(data.hidden).to.be.a('number');
            // expect(data.hidden).to.be(0);
            expect(data.sorting).to.be.a('number');
            // expect(data.sorting).to.be(0);
            expect(data.tags).to.be.a('string');
            // expect(data.tags).to.be("");

            done();
          }, function(error) {
            done(error);
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('testDelete', function() {
        it('should call testDelete successfully', function(done) {
          // TODO: uncomment, update parameter values for testDelete call and complete the assertions
          /*
          var id = 56;

          instance.testDelete(id).then(function(data) {
            // TODO: update response assertions
            expect(data).to.be.a(SeminarCatalogApi.Test);
            expect(data.syncFields).to.be.a('string');
            // expect(data.syncFields).to.be("");
            expect(data.title).to.be.a('string');
            // expect(data.title).to.be("");
            expect(data.description).to.be.a('string');
            // expect(data.description).to.be("");
            expect(data.type).to.be.a('number');
            // expect(data.type).to.be(0);
            expect(data.mandatory).to.be.a('number');
            // expect(data.mandatory).to.be(0);
            expect(data.maxPoints).to.be.a('number');
            // expect(data.maxPoints).to.be(0);
            expect(data.passmarkPercentage).to.be.a('number');
            // expect(data.passmarkPercentage).to.be(0);
            expect(data.specificTestId).to.be.a('string');
            // expect(data.specificTestId).to.be("");
            expect(data.id).to.be.a('number');
            // expect(data.id).to.be(0);
            expect(data.foreignId).to.be.a('string');
            // expect(data.foreignId).to.be("");
            expect(data.language).to.be.a('number');
            // expect(data.language).to.be(0);
            expect(data.createDate).to.be.a('number');
            // expect(data.createDate).to.be(0);
            expect(data.changeDate).to.be.a('number');
            // expect(data.changeDate).to.be(0);
            expect(data.deleted).to.be.a('number');
            // expect(data.deleted).to.be(0);
            expect(data.hidden).to.be.a('number');
            // expect(data.hidden).to.be(0);
            expect(data.sorting).to.be.a('number');
            // expect(data.sorting).to.be(0);
            expect(data.tags).to.be.a('string');
            // expect(data.tags).to.be("");

            done();
          }, function(error) {
            done(error);
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('testGet', function() {
        it('should call testGet successfully', function(done) {
          // TODO: uncomment, update parameter values for testGet call and complete the assertions
          /*
          var id = 56;

          instance.testGet(id).then(function(data) {
            // TODO: update response assertions
            expect(data).to.be.a(SeminarCatalogApi.Test);
            expect(data.syncFields).to.be.a('string');
            // expect(data.syncFields).to.be("");
            expect(data.title).to.be.a('string');
            // expect(data.title).to.be("");
            expect(data.description).to.be.a('string');
            // expect(data.description).to.be("");
            expect(data.type).to.be.a('number');
            // expect(data.type).to.be(0);
            expect(data.mandatory).to.be.a('number');
            // expect(data.mandatory).to.be(0);
            expect(data.maxPoints).to.be.a('number');
            // expect(data.maxPoints).to.be(0);
            expect(data.passmarkPercentage).to.be.a('number');
            // expect(data.passmarkPercentage).to.be(0);
            expect(data.specificTestId).to.be.a('string');
            // expect(data.specificTestId).to.be("");
            expect(data.id).to.be.a('number');
            // expect(data.id).to.be(0);
            expect(data.foreignId).to.be.a('string');
            // expect(data.foreignId).to.be("");
            expect(data.language).to.be.a('number');
            // expect(data.language).to.be(0);
            expect(data.createDate).to.be.a('number');
            // expect(data.createDate).to.be(0);
            expect(data.changeDate).to.be.a('number');
            // expect(data.changeDate).to.be(0);
            expect(data.deleted).to.be.a('number');
            // expect(data.deleted).to.be(0);
            expect(data.hidden).to.be.a('number');
            // expect(data.hidden).to.be(0);
            expect(data.sorting).to.be.a('number');
            // expect(data.sorting).to.be(0);
            expect(data.tags).to.be.a('string');
            // expect(data.tags).to.be("");

            done();
          }, function(error) {
            done(error);
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('testList', function() {
        it('should call testList successfully', function(done) {
          // TODO: uncomment testList call and complete the assertions
          /*

          instance.testList().then(function(data) {
            // TODO: update response assertions
            expect(data).to.be.a(SeminarCatalogApi.TestPaginationResult);
            expect(data.limit).to.be.a('number');
            // expect(data.limit).to.be(0);
            expect(data.offset).to.be.a('number');
            // expect(data.offset).to.be(0);
            expect(data.entryCount).to.be.a('number');
            // expect(data.entryCount).to.be(0);
            expect(data.maxEntryCount).to.be.a('number');
            // expect(data.maxEntryCount).to.be(0);
            {
              let dataCtr = data.entries;
              expect(dataCtr).to.be.an(Array);
              expect(dataCtr).to.not.be.empty();
              for (let p in dataCtr) {
                let data = dataCtr[p];
                expect(data).to.be.a(SeminarCatalogApi.Test);
                expect(data.syncFields).to.be.a('string');
                // expect(data.syncFields).to.be("");
                expect(data.title).to.be.a('string');
                // expect(data.title).to.be("");
                expect(data.description).to.be.a('string');
                // expect(data.description).to.be("");
                expect(data.type).to.be.a('number');
                // expect(data.type).to.be(0);
                expect(data.mandatory).to.be.a('number');
                // expect(data.mandatory).to.be(0);
                expect(data.maxPoints).to.be.a('number');
                // expect(data.maxPoints).to.be(0);
                expect(data.passmarkPercentage).to.be.a('number');
                // expect(data.passmarkPercentage).to.be(0);
                expect(data.specificTestId).to.be.a('string');
                // expect(data.specificTestId).to.be("");
                expect(data.id).to.be.a('number');
                // expect(data.id).to.be(0);
                expect(data.foreignId).to.be.a('string');
                // expect(data.foreignId).to.be("");
                expect(data.language).to.be.a('number');
                // expect(data.language).to.be(0);
                expect(data.createDate).to.be.a('number');
                // expect(data.createDate).to.be(0);
                expect(data.changeDate).to.be.a('number');
                // expect(data.changeDate).to.be(0);
                expect(data.deleted).to.be.a('number');
                // expect(data.deleted).to.be(0);
                expect(data.hidden).to.be.a('number');
                // expect(data.hidden).to.be(0);
                expect(data.sorting).to.be.a('number');
                // expect(data.sorting).to.be(0);
                expect(data.tags).to.be.a('string');
                // expect(data.tags).to.be("");
              }
            }

            done();
          }, function(error) {
            done(error);
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('testUpdate', function() {
        it('should call testUpdate successfully', function(done) {
          // TODO: uncomment, update parameter values for testUpdate call and complete the assertions
          /*
          var id = 56;

          instance.testUpdate(id).then(function(data) {
            // TODO: update response assertions
            expect(data).to.be.a(SeminarCatalogApi.Test);
            expect(data.syncFields).to.be.a('string');
            // expect(data.syncFields).to.be("");
            expect(data.title).to.be.a('string');
            // expect(data.title).to.be("");
            expect(data.description).to.be.a('string');
            // expect(data.description).to.be("");
            expect(data.type).to.be.a('number');
            // expect(data.type).to.be(0);
            expect(data.mandatory).to.be.a('number');
            // expect(data.mandatory).to.be(0);
            expect(data.maxPoints).to.be.a('number');
            // expect(data.maxPoints).to.be(0);
            expect(data.passmarkPercentage).to.be.a('number');
            // expect(data.passmarkPercentage).to.be(0);
            expect(data.specificTestId).to.be.a('string');
            // expect(data.specificTestId).to.be("");
            expect(data.id).to.be.a('number');
            // expect(data.id).to.be(0);
            expect(data.foreignId).to.be.a('string');
            // expect(data.foreignId).to.be("");
            expect(data.language).to.be.a('number');
            // expect(data.language).to.be(0);
            expect(data.createDate).to.be.a('number');
            // expect(data.createDate).to.be(0);
            expect(data.changeDate).to.be.a('number');
            // expect(data.changeDate).to.be(0);
            expect(data.deleted).to.be.a('number');
            // expect(data.deleted).to.be(0);
            expect(data.hidden).to.be.a('number');
            // expect(data.hidden).to.be(0);
            expect(data.sorting).to.be.a('number');
            // expect(data.sorting).to.be(0);
            expect(data.tags).to.be.a('string');
            // expect(data.tags).to.be("");

            done();
          }, function(error) {
            done(error);
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
