/*
 * SeminarCatalog API
 * Rest API for SeminarCatalog Administration
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@databay.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.12
 *
 * Do not edit the class manually.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SeminarCatalogApi);
  }
}(this, function(expect, SeminarCatalogApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Currency', function() {
      beforeEach(function() {
        instance = new SeminarCatalogApi.Currency();
      });

      it('should create an instance of Currency', function() {
        // TODO: update the code to test Currency
        expect(instance).to.be.a(SeminarCatalogApi.Currency);
      });

      it('should have the property syncFields (base name: "_syncFields")', function() {
        // TODO: update the code to test the property syncFields
        expect(instance).to.have.property('syncFields');
        // expect(instance.syncFields).to.be(expectedValueLiteral);
      });

      it('should have the property name (base name: "name")', function() {
        // TODO: update the code to test the property name
        expect(instance).to.have.property('name');
        // expect(instance.name).to.be(expectedValueLiteral);
      });

      it('should have the property localName (base name: "localName")', function() {
        // TODO: update the code to test the property localName
        expect(instance).to.have.property('localName');
        // expect(instance.localName).to.be(expectedValueLiteral);
      });

      it('should have the property englishName (base name: "englishName")', function() {
        // TODO: update the code to test the property englishName
        expect(instance).to.have.property('englishName');
        // expect(instance.englishName).to.be(expectedValueLiteral);
      });

      it('should have the property code (base name: "code")', function() {
        // TODO: update the code to test the property code
        expect(instance).to.have.property('code');
        // expect(instance.code).to.be(expectedValueLiteral);
      });

      it('should have the property symbolLeft (base name: "symbolLeft")', function() {
        // TODO: update the code to test the property symbolLeft
        expect(instance).to.have.property('symbolLeft');
        // expect(instance.symbolLeft).to.be(expectedValueLiteral);
      });

      it('should have the property symbolRight (base name: "symbolRight")', function() {
        // TODO: update the code to test the property symbolRight
        expect(instance).to.have.property('symbolRight');
        // expect(instance.symbolRight).to.be(expectedValueLiteral);
      });

      it('should have the property symbolSubLeft (base name: "symbolSubLeft")', function() {
        // TODO: update the code to test the property symbolSubLeft
        expect(instance).to.have.property('symbolSubLeft');
        // expect(instance.symbolSubLeft).to.be(expectedValueLiteral);
      });

      it('should have the property symbolSubRight (base name: "symbolSubRight")', function() {
        // TODO: update the code to test the property symbolSubRight
        expect(instance).to.have.property('symbolSubRight');
        // expect(instance.symbolSubRight).to.be(expectedValueLiteral);
      });

      it('should have the property thousandsPoint (base name: "thousandsPoint")', function() {
        // TODO: update the code to test the property thousandsPoint
        expect(instance).to.have.property('thousandsPoint');
        // expect(instance.thousandsPoint).to.be(expectedValueLiteral);
      });

      it('should have the property decimalPoint (base name: "decimalPoint")', function() {
        // TODO: update the code to test the property decimalPoint
        expect(instance).to.have.property('decimalPoint');
        // expect(instance.decimalPoint).to.be(expectedValueLiteral);
      });

      it('should have the property decimalDigits (base name: "decimalDigits")', function() {
        // TODO: update the code to test the property decimalDigits
        expect(instance).to.have.property('decimalDigits');
        // expect(instance.decimalDigits).to.be(expectedValueLiteral);
      });

      it('should have the property defaultCurrency (base name: "defaultCurrency")', function() {
        // TODO: update the code to test the property defaultCurrency
        expect(instance).to.have.property('defaultCurrency');
        // expect(instance.defaultCurrency).to.be(expectedValueLiteral);
      });

      it('should have the property exchangeRate (base name: "exchangeRate")', function() {
        // TODO: update the code to test the property exchangeRate
        expect(instance).to.have.property('exchangeRate');
        // expect(instance.exchangeRate).to.be(expectedValueLiteral);
      });

      it('should have the property exchangeRateDate (base name: "exchangeRateDate")', function() {
        // TODO: update the code to test the property exchangeRateDate
        expect(instance).to.have.property('exchangeRateDate');
        // expect(instance.exchangeRateDate).to.be(expectedValueLiteral);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property foreignId (base name: "foreignId")', function() {
        // TODO: update the code to test the property foreignId
        expect(instance).to.have.property('foreignId');
        // expect(instance.foreignId).to.be(expectedValueLiteral);
      });

      it('should have the property language (base name: "language")', function() {
        // TODO: update the code to test the property language
        expect(instance).to.have.property('language');
        // expect(instance.language).to.be(expectedValueLiteral);
      });

      it('should have the property createDate (base name: "createDate")', function() {
        // TODO: update the code to test the property createDate
        expect(instance).to.have.property('createDate');
        // expect(instance.createDate).to.be(expectedValueLiteral);
      });

      it('should have the property changeDate (base name: "changeDate")', function() {
        // TODO: update the code to test the property changeDate
        expect(instance).to.have.property('changeDate');
        // expect(instance.changeDate).to.be(expectedValueLiteral);
      });

      it('should have the property deleted (base name: "deleted")', function() {
        // TODO: update the code to test the property deleted
        expect(instance).to.have.property('deleted');
        // expect(instance.deleted).to.be(expectedValueLiteral);
      });

      it('should have the property hidden (base name: "hidden")', function() {
        // TODO: update the code to test the property hidden
        expect(instance).to.have.property('hidden');
        // expect(instance.hidden).to.be(expectedValueLiteral);
      });

      it('should have the property sorting (base name: "sorting")', function() {
        // TODO: update the code to test the property sorting
        expect(instance).to.have.property('sorting');
        // expect(instance.sorting).to.be(expectedValueLiteral);
      });

      it('should have the property tags (base name: "tags")', function() {
        // TODO: update the code to test the property tags
        expect(instance).to.have.property('tags');
        // expect(instance.tags).to.be(expectedValueLiteral);
      });

    });
  });

}));
