/*
 * SeminarCatalog API
 * Rest API for SeminarCatalog Administration
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@databay.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.12
 *
 * Do not edit the class manually.
 */

import {ApiClient} from './ApiClient';
import {Address} from './model/Address';
import {AllocationWaitingList} from './model/AllocationWaitingList';
import {BookingInterest} from './model/BookingInterest';
import {Category} from './model/Category';
import {Certificate} from './model/Certificate';
import {ContactPerson} from './model/ContactPerson';
import {Country} from './model/Country';
import {Coupon} from './model/Coupon';
import {CouponCode} from './model/CouponCode';
import {Currency} from './model/Currency';
import {EducationHistoryItem} from './model/EducationHistoryItem';
import {Event} from './model/Event';
import {Hotel} from './model/Hotel';
import {Language} from './model/Language';
import {Location} from './model/Location';
import {Media} from './model/Media';
import {Order} from './model/Order';
import {Organizer} from './model/Organizer';
import {Participant} from './model/Participant';
import {Participation} from './model/Participation';
import {ParticipationCode} from './model/ParticipationCode';
import {Partner} from './model/Partner';
import {PaymentMethod} from './model/PaymentMethod';
import {Price} from './model/Price';
import {Product} from './model/Product';
import {ProductVariant} from './model/ProductVariant';
import {ProviderInfo} from './model/ProviderInfo';
import {Receiver} from './model/Receiver';
import {Region} from './model/Region';
import {Restaurant} from './model/Restaurant';
import {RevenueAccount} from './model/RevenueAccount';
import {RoleDiscount} from './model/RoleDiscount';
import {Seminar} from './model/Seminar';
import {SeminarConfiguration} from './model/SeminarConfiguration';
import {Subscription} from './model/Subscription';
import {SubscriptionConfiguration} from './model/SubscriptionConfiguration';
import {SubscriptionPlan} from './model/SubscriptionPlan';
import {Task} from './model/Task';
import {Test} from './model/Test';
import {TestResult} from './model/TestResult';
import {Topic} from './model/Topic';
import {Trainer} from './model/Trainer';
import {User} from './model/User';
import {UserGroup} from './model/UserGroup';
import {Vat} from './model/Vat';
import {WaitingList} from './model/WaitingList';
import {AddressApi as AddressApiClass, AddressApiSingleton as AddressApi} from './api/AddressApi';
import {AllocationWaitingListApi as AllocationWaitingListApiClass, AllocationWaitingListApiSingleton as AllocationWaitingListApi} from './api/AllocationWaitingListApi';
import {BookingInterestApi as BookingInterestApiClass, BookingInterestApiSingleton as BookingInterestApi} from './api/BookingInterestApi';
import {CategoryApi as CategoryApiClass, CategoryApiSingleton as CategoryApi} from './api/CategoryApi';
import {CertificateApi as CertificateApiClass, CertificateApiSingleton as CertificateApi} from './api/CertificateApi';
import {ContactPersonApi as ContactPersonApiClass, ContactPersonApiSingleton as ContactPersonApi} from './api/ContactPersonApi';
import {CountryApi as CountryApiClass, CountryApiSingleton as CountryApi} from './api/CountryApi';
import {CouponApi as CouponApiClass, CouponApiSingleton as CouponApi} from './api/CouponApi';
import {CouponCodeApi as CouponCodeApiClass, CouponCodeApiSingleton as CouponCodeApi} from './api/CouponCodeApi';
import {CurrencyApi as CurrencyApiClass, CurrencyApiSingleton as CurrencyApi} from './api/CurrencyApi';
import {EducationHistoryItemApi as EducationHistoryItemApiClass, EducationHistoryItemApiSingleton as EducationHistoryItemApi} from './api/EducationHistoryItemApi';
import {EventApi as EventApiClass, EventApiSingleton as EventApi} from './api/EventApi';
import {HotelApi as HotelApiClass, HotelApiSingleton as HotelApi} from './api/HotelApi';
import {LanguageApi as LanguageApiClass, LanguageApiSingleton as LanguageApi} from './api/LanguageApi';
import {LocationApi as LocationApiClass, LocationApiSingleton as LocationApi} from './api/LocationApi';
import {MediaApi as MediaApiClass, MediaApiSingleton as MediaApi} from './api/MediaApi';
import {OrderApi as OrderApiClass, OrderApiSingleton as OrderApi} from './api/OrderApi';
import {OrganizerApi as OrganizerApiClass, OrganizerApiSingleton as OrganizerApi} from './api/OrganizerApi';
import {ParticipantApi as ParticipantApiClass, ParticipantApiSingleton as ParticipantApi} from './api/ParticipantApi';
import {ParticipationApi as ParticipationApiClass, ParticipationApiSingleton as ParticipationApi} from './api/ParticipationApi';
import {ParticipationCodeApi as ParticipationCodeApiClass, ParticipationCodeApiSingleton as ParticipationCodeApi} from './api/ParticipationCodeApi';
import {PartnerApi as PartnerApiClass, PartnerApiSingleton as PartnerApi} from './api/PartnerApi';
import {PaymentMethodApi as PaymentMethodApiClass, PaymentMethodApiSingleton as PaymentMethodApi} from './api/PaymentMethodApi';
import {PriceApi as PriceApiClass, PriceApiSingleton as PriceApi} from './api/PriceApi';
import {ProductApi as ProductApiClass, ProductApiSingleton as ProductApi} from './api/ProductApi';
import {ProductVariantApi as ProductVariantApiClass, ProductVariantApiSingleton as ProductVariantApi} from './api/ProductVariantApi';
import {ProviderInfoApi as ProviderInfoApiClass, ProviderInfoApiSingleton as ProviderInfoApi} from './api/ProviderInfoApi';
import {ReceiverApi as ReceiverApiClass, ReceiverApiSingleton as ReceiverApi} from './api/ReceiverApi';
import {RegionApi as RegionApiClass, RegionApiSingleton as RegionApi} from './api/RegionApi';
import {RestaurantApi as RestaurantApiClass, RestaurantApiSingleton as RestaurantApi} from './api/RestaurantApi';
import {RevenueAccountApi as RevenueAccountApiClass, RevenueAccountApiSingleton as RevenueAccountApi} from './api/RevenueAccountApi';
import {RoleDiscountApi as RoleDiscountApiClass, RoleDiscountApiSingleton as RoleDiscountApi} from './api/RoleDiscountApi';
import {SeminarApi as SeminarApiClass, SeminarApiSingleton as SeminarApi} from './api/SeminarApi';
import {SeminarConfigurationApi as SeminarConfigurationApiClass, SeminarConfigurationApiSingleton as SeminarConfigurationApi} from './api/SeminarConfigurationApi';
import {SubscriptionApi as SubscriptionApiClass, SubscriptionApiSingleton as SubscriptionApi} from './api/SubscriptionApi';
import {SubscriptionConfigurationApi as SubscriptionConfigurationApiClass, SubscriptionConfigurationApiSingleton as SubscriptionConfigurationApi} from './api/SubscriptionConfigurationApi';
import {SubscriptionPlanApi as SubscriptionPlanApiClass, SubscriptionPlanApiSingleton as SubscriptionPlanApi} from './api/SubscriptionPlanApi';
import {TaskApi as TaskApiClass, TaskApiSingleton as TaskApi} from './api/TaskApi';
import {TestApi as TestApiClass, TestApiSingleton as TestApi} from './api/TestApi';
import {TestResultApi as TestResultApiClass, TestResultApiSingleton as TestResultApi} from './api/TestResultApi';
import {TopicApi as TopicApiClass, TopicApiSingleton as TopicApi} from './api/TopicApi';
import {TrainerApi as TrainerApiClass, TrainerApiSingleton as TrainerApi} from './api/TrainerApi';
import {UserApi as UserApiClass, UserApiSingleton as UserApi} from './api/UserApi';
import {UserGroupApi as UserGroupApiClass, UserGroupApiSingleton as UserGroupApi} from './api/UserGroupApi';
import {VatApi as VatApiClass, VatApiSingleton as VatApi} from './api/VatApi';
import {WaitingListApi as WaitingListApiClass, WaitingListApiSingleton as WaitingListApi} from './api/WaitingListApi';


/**
* This project is the official Javascript API client implementation for the SeminarCatalog developed by the Databay AG..<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var SeminarCatalogApi = require('index'); // See note below*.
* var xxxSvc = new SeminarCatalogApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new SeminarCatalogApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new SeminarCatalogApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new SeminarCatalogApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Address model constructor.
     * @property {module:model/Address}
     */
    Address,

    /**
     * The AllocationWaitingList model constructor.
     * @property {module:model/AllocationWaitingList}
     */
    AllocationWaitingList,

    /**
     * The BookingInterest model constructor.
     * @property {module:model/BookingInterest}
     */
    BookingInterest,

    /**
     * The Category model constructor.
     * @property {module:model/Category}
     */
    Category,

    /**
     * The Certificate model constructor.
     * @property {module:model/Certificate}
     */
    Certificate,

    /**
     * The ContactPerson model constructor.
     * @property {module:model/ContactPerson}
     */
    ContactPerson,

    /**
     * The Country model constructor.
     * @property {module:model/Country}
     */
    Country,

    /**
     * The Coupon model constructor.
     * @property {module:model/Coupon}
     */
    Coupon,

    /**
     * The CouponCode model constructor.
     * @property {module:model/CouponCode}
     */
    CouponCode,

    /**
     * The Currency model constructor.
     * @property {module:model/Currency}
     */
    Currency,

    /**
     * The EducationHistoryItem model constructor.
     * @property {module:model/EducationHistoryItem}
     */
    EducationHistoryItem,

    /**
     * The Event model constructor.
     * @property {module:model/Event}
     */
    Event,

    /**
     * The Hotel model constructor.
     * @property {module:model/Hotel}
     */
    Hotel,

    /**
     * The Language model constructor.
     * @property {module:model/Language}
     */
    Language,

    /**
     * The Location model constructor.
     * @property {module:model/Location}
     */
    Location,

    /**
     * The Media model constructor.
     * @property {module:model/Media}
     */
    Media,

    /**
     * The Order model constructor.
     * @property {module:model/Order}
     */
    Order,

    /**
     * The Organizer model constructor.
     * @property {module:model/Organizer}
     */
    Organizer,

    /**
     * The Participant model constructor.
     * @property {module:model/Participant}
     */
    Participant,

    /**
     * The Participation model constructor.
     * @property {module:model/Participation}
     */
    Participation,

    /**
     * The ParticipationCode model constructor.
     * @property {module:model/ParticipationCode}
     */
    ParticipationCode,

    /**
     * The Partner model constructor.
     * @property {module:model/Partner}
     */
    Partner,

    /**
     * The PaymentMethod model constructor.
     * @property {module:model/PaymentMethod}
     */
    PaymentMethod,

    /**
     * The Price model constructor.
     * @property {module:model/Price}
     */
    Price,

    /**
     * The Product model constructor.
     * @property {module:model/Product}
     */
    Product,

    /**
     * The ProductVariant model constructor.
     * @property {module:model/ProductVariant}
     */
    ProductVariant,

    /**
     * The ProviderInfo model constructor.
     * @property {module:model/ProviderInfo}
     */
    ProviderInfo,

    /**
     * The Receiver model constructor.
     * @property {module:model/Receiver}
     */
    Receiver,

    /**
     * The Region model constructor.
     * @property {module:model/Region}
     */
    Region,

    /**
     * The Restaurant model constructor.
     * @property {module:model/Restaurant}
     */
    Restaurant,

    /**
     * The RevenueAccount model constructor.
     * @property {module:model/RevenueAccount}
     */
    RevenueAccount,

    /**
     * The RoleDiscount model constructor.
     * @property {module:model/RoleDiscount}
     */
    RoleDiscount,

    /**
     * The Seminar model constructor.
     * @property {module:model/Seminar}
     */
    Seminar,

    /**
     * The SeminarConfiguration model constructor.
     * @property {module:model/SeminarConfiguration}
     */
    SeminarConfiguration,

    /**
     * The Subscription model constructor.
     * @property {module:model/Subscription}
     */
    Subscription,

    /**
     * The SubscriptionConfiguration model constructor.
     * @property {module:model/SubscriptionConfiguration}
     */
    SubscriptionConfiguration,

    /**
     * The SubscriptionPlan model constructor.
     * @property {module:model/SubscriptionPlan}
     */
    SubscriptionPlan,

    /**
     * The Task model constructor.
     * @property {module:model/Task}
     */
    Task,

    /**
     * The Test model constructor.
     * @property {module:model/Test}
     */
    Test,

    /**
     * The TestResult model constructor.
     * @property {module:model/TestResult}
     */
    TestResult,

    /**
     * The Topic model constructor.
     * @property {module:model/Topic}
     */
    Topic,

    /**
     * The Trainer model constructor.
     * @property {module:model/Trainer}
     */
    Trainer,

    /**
     * The User model constructor.
     * @property {module:model/User}
     */
    User,

    /**
     * The UserGroup model constructor.
     * @property {module:model/UserGroup}
     */
    UserGroup,

    /**
     * The Vat model constructor.
     * @property {module:model/Vat}
     */
    Vat,

    /**
     * The WaitingList model constructor.
     * @property {module:model/WaitingList}
     */
    WaitingList,

    /**
    * The AddressApi service singleton.
    * @property {module:api/AddressInternalApi}
    */
    AddressApi,

    /**
    * The AllocationWaitingListApi service singleton.
    * @property {module:api/AllocationWaitingListInternalApi}
    */
    AllocationWaitingListApi,

    /**
    * The BookingInterestApi service singleton.
    * @property {module:api/BookingInterestInternalApi}
    */
    BookingInterestApi,

    /**
    * The CategoryApi service singleton.
    * @property {module:api/CategoryInternalApi}
    */
    CategoryApi,

    /**
    * The CertificateApi service singleton.
    * @property {module:api/CertificateInternalApi}
    */
    CertificateApi,

    /**
    * The ContactPersonApi service singleton.
    * @property {module:api/ContactPersonInternalApi}
    */
    ContactPersonApi,

    /**
    * The CountryApi service singleton.
    * @property {module:api/CountryInternalApi}
    */
    CountryApi,

    /**
    * The CouponApi service singleton.
    * @property {module:api/CouponInternalApi}
    */
    CouponApi,

    /**
    * The CouponCodeApi service singleton.
    * @property {module:api/CouponCodeInternalApi}
    */
    CouponCodeApi,

    /**
    * The CurrencyApi service singleton.
    * @property {module:api/CurrencyInternalApi}
    */
    CurrencyApi,

    /**
    * The EducationHistoryItemApi service singleton.
    * @property {module:api/EducationHistoryItemInternalApi}
    */
    EducationHistoryItemApi,

    /**
    * The EventApi service singleton.
    * @property {module:api/EventInternalApi}
    */
    EventApi,

    /**
    * The HotelApi service singleton.
    * @property {module:api/HotelInternalApi}
    */
    HotelApi,

    /**
    * The LanguageApi service singleton.
    * @property {module:api/LanguageInternalApi}
    */
    LanguageApi,

    /**
    * The LocationApi service singleton.
    * @property {module:api/LocationInternalApi}
    */
    LocationApi,

    /**
    * The MediaApi service singleton.
    * @property {module:api/MediaInternalApi}
    */
    MediaApi,

    /**
    * The OrderApi service singleton.
    * @property {module:api/OrderInternalApi}
    */
    OrderApi,

    /**
    * The OrganizerApi service singleton.
    * @property {module:api/OrganizerInternalApi}
    */
    OrganizerApi,

    /**
    * The ParticipantApi service singleton.
    * @property {module:api/ParticipantInternalApi}
    */
    ParticipantApi,

    /**
    * The ParticipationApi service singleton.
    * @property {module:api/ParticipationInternalApi}
    */
    ParticipationApi,

    /**
    * The ParticipationCodeApi service singleton.
    * @property {module:api/ParticipationCodeInternalApi}
    */
    ParticipationCodeApi,

    /**
    * The PartnerApi service singleton.
    * @property {module:api/PartnerInternalApi}
    */
    PartnerApi,

    /**
    * The PaymentMethodApi service singleton.
    * @property {module:api/PaymentMethodInternalApi}
    */
    PaymentMethodApi,

    /**
    * The PriceApi service singleton.
    * @property {module:api/PriceInternalApi}
    */
    PriceApi,

    /**
    * The ProductApi service singleton.
    * @property {module:api/ProductInternalApi}
    */
    ProductApi,

    /**
    * The ProductVariantApi service singleton.
    * @property {module:api/ProductVariantInternalApi}
    */
    ProductVariantApi,

    /**
    * The ProviderInfoApi service singleton.
    * @property {module:api/ProviderInfoInternalApi}
    */
    ProviderInfoApi,

    /**
    * The ReceiverApi service singleton.
    * @property {module:api/ReceiverInternalApi}
    */
    ReceiverApi,

    /**
    * The RegionApi service singleton.
    * @property {module:api/RegionInternalApi}
    */
    RegionApi,

    /**
    * The RestaurantApi service singleton.
    * @property {module:api/RestaurantInternalApi}
    */
    RestaurantApi,

    /**
    * The RevenueAccountApi service singleton.
    * @property {module:api/RevenueAccountInternalApi}
    */
    RevenueAccountApi,

    /**
    * The RoleDiscountApi service singleton.
    * @property {module:api/RoleDiscountInternalApi}
    */
    RoleDiscountApi,

    /**
    * The SeminarApi service singleton.
    * @property {module:api/SeminarInternalApi}
    */
    SeminarApi,

    /**
    * The SeminarConfigurationApi service singleton.
    * @property {module:api/SeminarConfigurationInternalApi}
    */
    SeminarConfigurationApi,

    /**
    * The SubscriptionApi service singleton.
    * @property {module:api/SubscriptionInternalApi}
    */
    SubscriptionApi,

    /**
    * The SubscriptionConfigurationApi service singleton.
    * @property {module:api/SubscriptionConfigurationInternalApi}
    */
    SubscriptionConfigurationApi,

    /**
    * The SubscriptionPlanApi service singleton.
    * @property {module:api/SubscriptionPlanInternalApi}
    */
    SubscriptionPlanApi,

    /**
    * The TaskApi service singleton.
    * @property {module:api/TaskInternalApi}
    */
    TaskApi,

    /**
    * The TestApi service singleton.
    * @property {module:api/TestInternalApi}
    */
    TestApi,

    /**
    * The TestResultApi service singleton.
    * @property {module:api/TestResultInternalApi}
    */
    TestResultApi,

    /**
    * The TopicApi service singleton.
    * @property {module:api/TopicInternalApi}
    */
    TopicApi,

    /**
    * The TrainerApi service singleton.
    * @property {module:api/TrainerInternalApi}
    */
    TrainerApi,

    /**
    * The UserApi service singleton.
    * @property {module:api/UserInternalApi}
    */
    UserApi,

    /**
    * The UserGroupApi service singleton.
    * @property {module:api/UserGroupInternalApi}
    */
    UserGroupApi,

    /**
    * The VatApi service singleton.
    * @property {module:api/VatInternalApi}
    */
    VatApi,

    /**
    * The WaitingListApi service singleton.
    * @property {module:api/WaitingListInternalApi}
    */
    WaitingListApi,

    /**
    * The AddressApiClass service constructor.
    * @property {module:api/AddressInternalApi}
    */
    AddressApiClass,

    /**
    * The AllocationWaitingListApiClass service constructor.
    * @property {module:api/AllocationWaitingListInternalApi}
    */
    AllocationWaitingListApiClass,

    /**
    * The BookingInterestApiClass service constructor.
    * @property {module:api/BookingInterestInternalApi}
    */
    BookingInterestApiClass,

    /**
    * The CategoryApiClass service constructor.
    * @property {module:api/CategoryInternalApi}
    */
    CategoryApiClass,

    /**
    * The CertificateApiClass service constructor.
    * @property {module:api/CertificateInternalApi}
    */
    CertificateApiClass,

    /**
    * The ContactPersonApiClass service constructor.
    * @property {module:api/ContactPersonInternalApi}
    */
    ContactPersonApiClass,

    /**
    * The CountryApiClass service constructor.
    * @property {module:api/CountryInternalApi}
    */
    CountryApiClass,

    /**
    * The CouponApiClass service constructor.
    * @property {module:api/CouponInternalApi}
    */
    CouponApiClass,

    /**
    * The CouponCodeApiClass service constructor.
    * @property {module:api/CouponCodeInternalApi}
    */
    CouponCodeApiClass,

    /**
    * The CurrencyApiClass service constructor.
    * @property {module:api/CurrencyInternalApi}
    */
    CurrencyApiClass,

    /**
    * The EducationHistoryItemApiClass service constructor.
    * @property {module:api/EducationHistoryItemInternalApi}
    */
    EducationHistoryItemApiClass,

    /**
    * The EventApiClass service constructor.
    * @property {module:api/EventInternalApi}
    */
    EventApiClass,

    /**
    * The HotelApiClass service constructor.
    * @property {module:api/HotelInternalApi}
    */
    HotelApiClass,

    /**
    * The LanguageApiClass service constructor.
    * @property {module:api/LanguageInternalApi}
    */
    LanguageApiClass,

    /**
    * The LocationApiClass service constructor.
    * @property {module:api/LocationInternalApi}
    */
    LocationApiClass,

    /**
    * The MediaApiClass service constructor.
    * @property {module:api/MediaInternalApi}
    */
    MediaApiClass,

    /**
    * The OrderApiClass service constructor.
    * @property {module:api/OrderInternalApi}
    */
    OrderApiClass,

    /**
    * The OrganizerApiClass service constructor.
    * @property {module:api/OrganizerInternalApi}
    */
    OrganizerApiClass,

    /**
    * The ParticipantApiClass service constructor.
    * @property {module:api/ParticipantInternalApi}
    */
    ParticipantApiClass,

    /**
    * The ParticipationApiClass service constructor.
    * @property {module:api/ParticipationInternalApi}
    */
    ParticipationApiClass,

    /**
    * The ParticipationCodeApiClass service constructor.
    * @property {module:api/ParticipationCodeInternalApi}
    */
    ParticipationCodeApiClass,

    /**
    * The PartnerApiClass service constructor.
    * @property {module:api/PartnerInternalApi}
    */
    PartnerApiClass,

    /**
    * The PaymentMethodApiClass service constructor.
    * @property {module:api/PaymentMethodInternalApi}
    */
    PaymentMethodApiClass,

    /**
    * The PriceApiClass service constructor.
    * @property {module:api/PriceInternalApi}
    */
    PriceApiClass,

    /**
    * The ProductApiClass service constructor.
    * @property {module:api/ProductInternalApi}
    */
    ProductApiClass,

    /**
    * The ProductVariantApiClass service constructor.
    * @property {module:api/ProductVariantInternalApi}
    */
    ProductVariantApiClass,

    /**
    * The ProviderInfoApiClass service constructor.
    * @property {module:api/ProviderInfoInternalApi}
    */
    ProviderInfoApiClass,

    /**
    * The ReceiverApiClass service constructor.
    * @property {module:api/ReceiverInternalApi}
    */
    ReceiverApiClass,

    /**
    * The RegionApiClass service constructor.
    * @property {module:api/RegionInternalApi}
    */
    RegionApiClass,

    /**
    * The RestaurantApiClass service constructor.
    * @property {module:api/RestaurantInternalApi}
    */
    RestaurantApiClass,

    /**
    * The RevenueAccountApiClass service constructor.
    * @property {module:api/RevenueAccountInternalApi}
    */
    RevenueAccountApiClass,

    /**
    * The RoleDiscountApiClass service constructor.
    * @property {module:api/RoleDiscountInternalApi}
    */
    RoleDiscountApiClass,

    /**
    * The SeminarApiClass service constructor.
    * @property {module:api/SeminarInternalApi}
    */
    SeminarApiClass,

    /**
    * The SeminarConfigurationApiClass service constructor.
    * @property {module:api/SeminarConfigurationInternalApi}
    */
    SeminarConfigurationApiClass,

    /**
    * The SubscriptionApiClass service constructor.
    * @property {module:api/SubscriptionInternalApi}
    */
    SubscriptionApiClass,

    /**
    * The SubscriptionConfigurationApiClass service constructor.
    * @property {module:api/SubscriptionConfigurationInternalApi}
    */
    SubscriptionConfigurationApiClass,

    /**
    * The SubscriptionPlanApiClass service constructor.
    * @property {module:api/SubscriptionPlanInternalApi}
    */
    SubscriptionPlanApiClass,

    /**
    * The TaskApiClass service constructor.
    * @property {module:api/TaskInternalApi}
    */
    TaskApiClass,

    /**
    * The TestApiClass service constructor.
    * @property {module:api/TestInternalApi}
    */
    TestApiClass,

    /**
    * The TestResultApiClass service constructor.
    * @property {module:api/TestResultInternalApi}
    */
    TestResultApiClass,

    /**
    * The TopicApiClass service constructor.
    * @property {module:api/TopicInternalApi}
    */
    TopicApiClass,

    /**
    * The TrainerApiClass service constructor.
    * @property {module:api/TrainerInternalApi}
    */
    TrainerApiClass,

    /**
    * The UserApiClass service constructor.
    * @property {module:api/UserInternalApi}
    */
    UserApiClass,

    /**
    * The UserGroupApiClass service constructor.
    * @property {module:api/UserGroupInternalApi}
    */
    UserGroupApiClass,

    /**
    * The VatApiClass service constructor.
    * @property {module:api/VatInternalApi}
    */
    VatApiClass,

    /**
    * The WaitingListApiClass service constructor.
    * @property {module:api/WaitingListInternalApi}
    */
    WaitingListApiClass
};
